(define (square x)
  (* x x))
(define (cube x)
  (* x x x))
(define (abs x)
  (if (< x 0)
    (- x)
    x))
(define (good-enough? guess x)
  (< (abs (- (cube guess) x)) 0.001))
(define (average x y)
  (/ (+ x y) 2))
(define (improve guess x)
  (/
    (+ (/ x (square guess)) (* 2 guess))
    3))
(define (cbdrt-iter guess x)
  (if (good-enough? guess x)
    guess
    (cbdrt-iter (improve guess x)
	       x)))
(define (cbdrt x)
  (cbdrt-iter 1.0 x))
